<?php

namespace App\Faker;

class DashboardDataFaker
{
    public static function fake()
    {
        return [
            'data' => [
                [
                    'device_id' => 1,
                    'Machinery' => 'Aux Engine 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 454.8,
                    'Ubc' => 453.79,
                    'Uca' => 451.53,
                    'IaTHD' => 45.4,
                    'IbTHD' => 41.3,
                    'IcTHD' => 45.2,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 21468.9,
                    'KWH' => 49.8,
                    'F' => 59.96,
                    'Category' => 'Generator',
                    'Ratio' => 300,
                    'running' => false
                ],
                [
                    'device_id' => 2,
                    'Machinery' => 'Aux Engine 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 0,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0.2,
                    'KWH' => 9.5,
                    'F' => 65,
                    'Category' => 'Generator',
                    'Ratio' => 300,
                    'running' => false
                ],
                [
                    'device_id' => 3,
                    'Machinery' => 'Aux Engine 3',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 454.98,
                    'Ubc' => 454.95,
                    'Uca' => 454.95,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 131.5,
                    'KWH' => 10.5,
                    'F' => 60.07,
                    'Category' => 'Generator',
                    'Ratio' => 300,
                    'running' => false
                ],
                [
                    'device_id' => 4,
                    'Machinery' => 'Main/Vac Cond/Cooling SW Pump 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 4.14,
                    'Ib' => 0,
                    'Ic' => 4.12,
                    'Uab' => 146.1,
                    'Ubc' => 0,
                    'Uca' => 146.1,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 1,
                    'Ptot' => -0.002,
                    'PFtot' => -0.07,
                    'KVARH' => 288.6,
                    'KWH' => 299.9,
                    'F' => 60.09,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 20,
                    'running' => false
                ],
                [
                    'device_id' => 5,
                    'Machinery' => 'Main/Vac Cond/Cooling SW Pump 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 3.3,
                    'Ib' => 0,
                    'Ic' => 3.32,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 17.36,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 1,
                    'Ptot' => -0.001,
                    'PFtot' => -0.144,
                    'KVARH' => 234.9,
                    'KWH' => 0.6,
                    'F' => 60.14,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 20,
                    'running' => false
                ],
                [
                    'device_id' => 6,
                    'Machinery' => 'Main/Vac Cond/Cooling SW Pump 3',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 88.44,
                    'Ib' => 90,
                    'Ic' => 87.74,
                    'Uab' => 454.05,
                    'Ubc' => 454.45,
                    'Uca' => 454.05,
                    'IaTHD' => 5.8,
                    'IbTHD' => 5.3,
                    'IcTHD' => 5.5,
                    'Iunbal' => 0.025,
                    'Ptot' => 2.033,
                    'PFtot' => 0.876,
                    'KVARH' => 32564.5,
                    'KWH' => 60370.6,
                    'F' => 60.11,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 20,
                    'running' => true
                ],
                [
                    'device_id' => 7,
                    'Machinery' => 'Main Engine Lube Oil Pump 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 187.15,
                    'Ubc' => 0,
                    'Uca' => 187.46,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 155.9,
                    'KWH' => 0,
                    'F' => 60.1,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 40,
                    'running' => false
                ],
                [
                    'device_id' => 8,
                    'Machinery' => 'Main Engine Lube Oil Pump 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 40.28,
                    'Ib' => 40.84,
                    'Ic' => 41.76,
                    'Uab' => 455.17,
                    'Ubc' => 454.99,
                    'Uca' => 452.94,
                    'IaTHD' => 8.7,
                    'IbTHD' => 7.6,
                    'IcTHD' => 7.5,
                    'Iunbal' => 0.034,
                    'Ptot' => -0.526,
                    'PFtot' => -0.999,
                    'KVARH' => 1.6,
                    'KWH' => 0.1,
                    'F' => 60.09,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 40,
                    'running' => true
                ],
                [
                    'device_id' => 9,
                    'Machinery' => 'Main Engine Aux Blower 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 0,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0,
                    'KWH' => 0,
                    'F' => 0,
                    'Category' => 'Centrifugal Blower',
                    'Ratio' => 20,
                    'running' => false
                ],
                [
                    'device_id' => 10,
                    'Machinery' => 'Main Engine Aux Blower 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 1.3,
                    'Ib' => 0,
                    'Ic' => 1.26,
                    'Uab' => 454.9,
                    'Ubc' => 455.17,
                    'Uca' => 453.87,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 1,
                    'Ptot' => -0.014,
                    'PFtot' => -0.476,
                    'KVARH' => 0,
                    'KWH' => 0,
                    'F' => 60.07,
                    'Category' => 'Centrifugal Blower',
                    'Ratio' => 20,
                    'running' => false
                ],
                [
                    'device_id' => 11,
                    'Machinery' => 'Main Engine Jacket Cooling Water Pump 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 456.03,
                    'Ubc' => 454.87,
                    'Uca' => 453.37,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0,
                    'KWH' => 163.9,
                    'F' => 60.11,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 10,
                    'running' => false
                ],
                [
                    'device_id' => 12,
                    'Machinery' => 'Main Engine Jacket Cooling Water Pump 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 15.19,
                    'Ib' => 15.26,
                    'Ic' => 15.51,
                    'Uab' => 454.13,
                    'Ubc' => 453.93,
                    'Uca' => 454.67,
                    'IaTHD' => 5.7,
                    'IbTHD' => 5.9,
                    'IcTHD' => 5.8,
                    'Iunbal' => 0.021,
                    'Ptot' => -0.676,
                    'PFtot' => -0.832,
                    'KVARH' => 0,
                    'KWH' => 0.1,
                    'F' => 60.13,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 10,
                    'running' => true
                ],
                [
                    'device_id' => 13,
                    'Machinery' => 'Ballast Pump',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 291.8,
                    'Ib' => 297,
                    'Ic' => 291.4,
                    'Uab' => 449.63,
                    'Ubc' => 450.04,
                    'Uca' => 450.28,
                    'IaTHD' => 1.5,
                    'IbTHD' => 0,
                    'IcTHD' => 1.1,
                    'Iunbal' => 0.019,
                    'Ptot' => 1.233,
                    'PFtot' => 0.84,
                    'KVARH' => 0.5,
                    'KWH' => 8148.2,
                    'F' => 59.96,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 100,
                    'running' => true
                ],
                [
                    'device_id' => 14,
                    'Machinery' => 'Aux Boiler FD Fan',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 453.93,
                    'Ubc' => 454.74,
                    'Uca' => 454.25,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0,
                    'KWH' => 114,
                    'F' => 60.1,
                    'Category' => 'Centrifugal Blower',
                    'Ratio' => 40,
                    'running' => false
                ],
                [
                    'device_id' => 15,
                    'Machinery' => 'IG Blower 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 450.65,
                    'Ubc' => 450.57,
                    'Uca' => 450.75,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0,
                    'KWH' => 3798.4,
                    'F' => 59.97,
                    'Category' => 'Centrifugal Blower',
                    'Ratio' => 50,
                    'running' => false
                ],
                [
                    'device_id' => 16,
                    'Machinery' => 'IG Blower 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 454.78,
                    'Ubc' => 454.5,
                    'Uca' => 454.78,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0.8,
                    'KWH' => 15.9,
                    'F' => 60.09,
                    'Category' => 'Centrifugal Blower',
                    'Ratio' => 50,
                    'running' => false
                ],
                [
                    'device_id' => 17,
                    'Machinery' => 'IG Cooling SW Pump',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 0,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0,
                    'KWH' => 0,
                    'F' => 0,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 20,
                    'running' => false
                ],
                [
                    'device_id' => 18,
                    'Machinery' => 'Central Cooling FW Pump 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0.54,
                    'Ic' => 0.55,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 16.4,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 1,
                    'Ptot' => 0,
                    'PFtot' => -0.046,
                    'KVARH' => 21658.4,
                    'KWH' => 0.3,
                    'F' => 60.09,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 15,
                    'running' => false
                ],
                [
                    'device_id' => 19,
                    'Machinery' => 'Central Cooling FW Pump 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 45.74,
                    'Ib' => 44.62,
                    'Ic' => 44.98,
                    'Uab' => 453.9,
                    'Ubc' => 455.07,
                    'Uca' => 454.47,
                    'IaTHD' => 6.2,
                    'IbTHD' => 6.2,
                    'IcTHD' => 6.7,
                    'Iunbal' => 0.025,
                    'Ptot' => -0.722,
                    'PFtot' => -0.897,
                    'KVARH' => 0,
                    'KWH' => 0,
                    'F' => 60.08,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 15,
                    'running' => true
                ],
                [
                    'device_id' => 20,
                    'Machinery' => 'Central Cooling FW Pump 3',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0.51,
                    'Ib' => 0,
                    'Ic' => 0.51,
                    'Uab' => 454.77,
                    'Ubc' => 455.22,
                    'Uca' => 454.31,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 1,
                    'Ptot' => 0.004,
                    'PFtot' => 0.774,
                    'KVARH' => 0,
                    'KWH' => 90.2,
                    'F' => 60.08,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 15,
                    'running' => false
                ],
                [
                    'device_id' => 21,
                    'Machinery' => 'AC Compressor 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 0,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0,
                    'KWH' => 0,
                    'F' => 0,
                    'Category' => 'AC',
                    'Ratio' => 20,
                    'running' => false
                ],
                [
                    'device_id' => 22,
                    'Machinery' => 'AC Compressor 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 0,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0,
                    'KWH' => 0,
                    'F' => 0,
                    'Category' => 'AC',
                    'Ratio' => 20,
                    'running' => false
                ],
                [
                    'device_id' => 23,
                    'Machinery' => 'MAC 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 0,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 2664,
                    'KWH' => 268.4,
                    'F' => 59.55,
                    'Category' => 'Air Compressor',
                    'Ratio' => 30,
                    'running' => false
                ],
                [
                    'device_id' => 24,
                    'Machinery' => 'MAC 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 0,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 1722.1,
                    'KWH' => 0,
                    'F' => 60.96,
                    'Category' => 'Air Compressor',
                    'Ratio' => 30,
                    'running' => false
                ],
                [
                    'device_id' => 25,
                    'Machinery' => 'Bilge Fire and GS Pump 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 5.76,
                    'Uab' => 186.89,
                    'Ubc' => 186.26,
                    'Uca' => 0,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 1,
                    'Ptot' => 0,
                    'PFtot' => 1,
                    'KVARH' => 39.8,
                    'KWH' => 1419.6,
                    'F' => 60.1,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 40,
                    'running' => false
                ],
                [
                    'device_id' => 26,
                    'Machinery' => 'Bilge Fire and GS Pump 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 185.11,
                    'Ubc' => 0,
                    'Uca' => 185.08,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0,
                    'KWH' => 0,
                    'F' => 59.99,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 40,
                    'running' => false
                ],
                [
                    'device_id' => 27,
                    'Machinery' => 'HYD Deck Machinery FWD',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 455.05,
                    'Ubc' => 453.62,
                    'Uca' => 454.48,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 204,
                    'KWH' => 99.7,
                    'F' => 60.1,
                    'Category' => 'HYD',
                    'Ratio' => 30,
                    'running' => false
                ],
                [
                    'device_id' => 28,
                    'Machinery' => 'Steering Gear No 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 0,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0,
                    'KWH' => 0,
                    'F' => 0,
                    'Category' => 'Steering gear',
                    'Ratio' => 30,
                    'running' => false
                ],
                [
                    'device_id' => 29,
                    'Machinery' => 'EGCS SW Water Pump 1',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 453.9,
                    'Ubc' => 454.02,
                    'Uca' => 454.89,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 7.5,
                    'KWH' => 3.8,
                    'F' => 60.08,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 70,
                    'running' => false
                ],
                [
                    'device_id' => 30,
                    'Machinery' => 'EGCS SW Water Pump 2',
                    'Date' => '2020-02-11 20:33:00',
                    'Ia' => 0,
                    'Ib' => 0,
                    'Ic' => 0,
                    'Uab' => 0,
                    'Ubc' => 0,
                    'Uca' => 0,
                    'IaTHD' => 0,
                    'IbTHD' => 0,
                    'IcTHD' => 0,
                    'Iunbal' => 0,
                    'Ptot' => 0,
                    'PFtot' => 0,
                    'KVARH' => 0,
                    'KWH' => 0,
                    'F' => 0,
                    'Category' => 'Centrifugal Pump',
                    'Ratio' => 70,
                    'running' => false
                ]
            ]
        ];
    }
}
